### PR TITLE
Update assets.h

### PR DESCRIPTION
**Pull request by aeiadreams**
hello

### CODE REVIEW

**Comment by aeiadreams** [comment]
Please help

**Comment by TriForceX** [comment]
What is this update for?

**Comment by aeiadreams** [comment]
i just want to make a custom logo for my powkiddy v90 but i dont really know if i did the right thing sorry

**Comment by TriForceX** [comment]
Ok, in your fork every time you make a change through the website it will prompt the pull-request option to send your changes to the parent/original project, thats why you are here now. but if you want make changes only for yourself you could do the same way without making the pull-requests, just keep the branch created (in your case "patch-1") and get the executable file from your repository builds. the project already came prepared with auto-builds, and it will be triggered each time you push/save changes in your project.

image

Sometimes is not an instant build so you have to wait. Once is finished you can access your current build and get the compiled logo app. (uClibc is compatible with cfw 1.3.3 and 2.0 uclibc and musl version is compatible with 2.0 musl version only).

image

You can continue making modifications to the current branch (change branch to patch-1 in your repository home page) and save the changes to generate a new compilation on the Actions tab.

image

You could learn the Git and GitHub basics so you can also have a complete separated branch for all your changes and/or get updates from original project by time to time.

btw i tested yours and looks fine:

image

you could change the background color to white 😃 in the file main.cpp between line 17 to 20 changing background R G B values to 255 each one.

**Comment by TriForceX** [comment]
Good news for you, @Apaczer updated the code and now you can add your logo in png format and sound in wav format, so get the latest version and try it, now is easier to do it 😃 (remember to skip the pull-request task)

**Comment by aeiadreams** [comment]
can you make it transparent i mean can you make it without the white background on my PNG? and upload it

**Comment by aeiadreams** [comment]
can you make it transparent i mean can you make it without the white background on my PNG? and upload it

🎼🎮 𝕌𝕜𝕚𝕟𝕚𝕟𝕒𝕞® 🕹️👾

**Pull request closed without merging**
